"""Add email_threads, email_messages, and email_attachments tables

Revision ID: v3_email_content_tables
Revises: v2_email_accounts_table
Create Date: 2024-07-05 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'v3_email_content_tables'
down_revision: Union[str, None] = 'v2_email_accounts_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_id'), 'email_threads', ['id'], unique=False)
    op.create_index(op.f('ix_email_threads_subject'), 'email_threads', ['subject'], unique=False)
    op.create_index(op.f('ix_email_threads_user_id'), 'email_threads', ['user_id'], unique=False)

    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id_header', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sender_address', sa.String(), nullable=True),
    sa.Column('recipients_to', sa.JSON(), nullable=True),
    sa.Column('recipients_cc', sa.JSON(), nullable=True),
    sa.Column('recipients_bcc', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('in_reply_to_header', sa.String(), nullable=True),
    sa.Column('references_header', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('is_fetched_complete', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_email_account_id'), 'email_messages', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False)
    op.create_index(op.f('ix_email_messages_in_reply_to_header'), 'email_messages', ['in_reply_to_header'], unique=False)
    op.create_index(op.f('ix_email_messages_message_id_header'), 'email_messages', ['message_id_header'], unique=True)
    op.create_index(op.f('ix_email_messages_received_at'), 'email_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_email_messages_sender_address'), 'email_messages', ['sender_address'], unique=False)
    op.create_index(op.f('ix_email_messages_sent_at'), 'email_messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_email_messages_subject'), 'email_messages', ['subject'], unique=False)
    op.create_index(op.f('ix_email_messages_thread_id'), 'email_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_messages_user_id'), 'email_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_messages_is_read'), 'email_messages', ['is_read'], unique=False)


    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_message_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=True), # If storing on disk/S3
    # sa.Column('content_bytes', sa.LargeBinary(), nullable=True), # If storing in DB
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachments_content_id'), 'email_attachments', ['content_id'], unique=False)
    op.create_index(op.f('ix_email_attachments_email_message_id'), 'email_attachments', ['email_message_id'], unique=False)
    op.create_index(op.f('ix_email_attachments_id'), 'email_attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_attachments_id'), table_name='email_attachments')
    op.drop_index(op.f('ix_email_attachments_email_message_id'), table_name='email_attachments')
    op.drop_index(op.f('ix_email_attachments_content_id'), table_name='email_attachments')
    op.drop_table('email_attachments')

    op.drop_index(op.f('ix_email_messages_user_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_subject'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_sent_at'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_sender_address'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_received_at'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_message_id_header'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_in_reply_to_header'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_email_account_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_is_read'), table_name='email_messages')
    op.drop_table('email_messages')

    op.drop_index(op.f('ix_email_threads_user_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_subject'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_id'), table_name='email_threads')
    op.drop_table('email_threads')
    # ### end Alembic commands ###
