"""Update EmailThread model with last_message_at, snippet, and participants_json

Revision ID: v4_update_email_thread
Revises: v3_email_content_tables
Create Date: 2024-07-05 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'v4_update_email_thread'
down_revision: Union[str, None] = 'v3_email_content_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjust if necessary ###
    op.add_column('email_threads', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('email_threads', sa.Column('snippet', sa.String(length=255), nullable=True))
    op.add_column('email_threads', sa.Column('participants_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_email_threads_last_message_at'), 'email_threads', ['last_message_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjust if necessary ###
    op.drop_index(op.f('ix_email_threads_last_message_at'), table_name='email_threads')
    op.drop_column('email_threads', 'participants_json')
    op.drop_column('email_threads', 'snippet')
    op.drop_column('email_threads', 'last_message_at')
    # ### end Alembic commands ###
