"""Add category to email_messages table

Revision ID: v5_category_email_message
Revises: v4_update_email_thread
Create Date: 2024-07-05 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.constants import DEFAULT_CATEGORY # To set a server default if desired


# revision identifiers, used by Alembic.
revision: str = 'v5_category_email_message'
down_revision: Union[str, None] = 'v4_update_email_thread'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('category', sa.String(length=50), nullable=True, server_default=DEFAULT_CATEGORY))
    op.create_index(op.f('ix_email_messages_category'), 'email_messages', ['category'], unique=False)
    # ### end Alembic commands ###

    # If we want to ensure existing rows get the default category value immediately (not just on new inserts)
    # This depends on the DB and specific needs. For new tables or if NULL is acceptable temporarily,
    # server_default is often enough.
    # Example: op.execute(f"UPDATE email_messages SET category = '{DEFAULT_CATEGORY}' WHERE category IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_category'), table_name='email_messages')
    op.drop_column('email_messages', 'category')
    # ### end Alembic commands ###
