"""Add content_bytes to email_attachments table

Revision ID: v7_attachment_content
Revises: v6_complaint_data
Create Date: 2024-07-07 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'v7_attachment_content'
down_revision: Union[str, None] = 'v6_complaint_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_attachments', sa.Column('content_bytes', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_attachments', 'content_bytes')
    # ### end Alembic commands ###
