"""Add index to extracted_at on complaint_suggestions table

Revision ID: v9_complaint_extracted_at_idx
Revises: v8_thread_account_link
Create Date: 2024-07-09 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'v9_complaint_extracted_at_idx'
down_revision: Union[str, None] = 'v8_thread_account_link'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_complaint_suggestions_extracted_at'), 'complaint_suggestions', ['extracted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_suggestions_extracted_at'), table_name='complaint_suggestions')
    # ### end Alembic commands ###
